### PR TITLE
Add stroke and stroke-width (SVG)

### PR DESCRIPTION
**Pull request by princemaple**
visual_css_ _mubook

### CODE REVIEW

**Comment by princemaple** [comment]
@MarioRicalde This PR adds these two properties: `stroke` and `stroke-width`

**Comment by MarioRicalde** [comment]
thanks @princemaple - CCing @princemaple

**Comment by princemaple** [comment]
No problem!

**Comment by princemaple** [comment]
@MarioRicalde will this be merged anytime soon?

**Comment by princemaple** [comment]
@MarioRicalde bump

**Comment by EnriqueCanals** [comment]
:+1: looks good to go

**Pull request merged**
