### PR TITLE
support svg elements/properties

### PR DESCRIPTION
**Pull request by schmurfy**
I have been working more with svg elements lately (with d3.js) and having half my stylesheets highlighted as error is really annoying.
is there a version of this bundle supporting svg and if not would a pull request to add svg support be accepted ?

here is an example of svg stylesheet:

``` css
line {
  fill: none;
  stroke-width: 2px;
  stroke: black;
}
```

here both "stroke" and "stroke-width" and it would be true if it was html but it is not :(

### CODE REVIEW

**Comment by hbrls** [comment]
@schmurfy Hey, what's the progress here?

**Comment by schmurfy** [comment]
I would stay that is still waiting for review xD
That's the version I use and it seems to work fine for me.

**Comment by hbrls** [comment]
@MarioRicalde come on friends, save the world please :octocat:

**Comment by MarioRicalde** [comment]
Gentlemen,

> We can’t automatically merge this pull request.

That's what I get at the moment. I plan to resume working on this soon. 

@EnriqueCanals can you please give a crack at this and get it merged?

**Comment by schmurfy** [comment]
Since everything is on one line that's not a surprise it can't be merged automatically, especially since this pull request is a few years old xD

**Pull request closed without merging**
